### ISSUE TITLE
[BUG]: KeyError: 'Zone Lights Total Heating Rate(East Zone)'

### ISSUE THREAD

**Issue by kad99kev** [ugr-sail/sinergym#249]
### Bug 🐛
Using the normalise wrapper will cause a KeyError when using the `Eplus-datacenter` environment.

### To Reproduce

Minimal example:

```python
import gym
import numpy as np

import sinergym
from sinergym.utils.wrappers import LoggerWrapper, NormalizeObservation
from sinergym.utils.constants import RANGES_DATACENTER

env = gym.make('Eplus-datacenter-hot-discrete-v1')
env = NormalizeObservation(env, ranges=RANGES_DATACENTER)
env = LoggerWrapper(env)

observation = env.reset()

for i in range(1):
    action = env.action_space.sample()
    print("Action taken: ", action)
    # take selected action in environment
    observation, reward, done, info = env.step(action)
env.close()
```

Error:

```bash
Traceback (most recent call last):
  File "/workspaces/sinergym/try_env.py", line 12, in <module>
    observation = env.reset()
  File "/workspaces/sinergym/sinergym/utils/wrappers.py", line 236, in reset
    obs = self.env.reset()
  File "/usr/local/lib/python3.10/dist-packages/gym/core.py", line 320, in reset
    return self.observation(observation)
  File "/workspaces/sinergym/sinergym/utils/wrappers.py", line 44, in observation
    if(self.ranges[variable][1] - self.ranges[variable][0] == 0):
KeyError: 'Zone Lights Total Heating Rate(East Zone)'
```

### Expected behavior

The observation values should be normalised like in the given [example](https://github.com/ugr-sail/sinergym/blob/main/examples/wrappers_examples.ipynb).

### System Info

Describe the characteristic of your environment:
 * Describe how Sinergym was installed - Using Docker container.
 * Sinergym Version - 2.1.1
 * OS: Mac OS - Apple Silicon
 * Python version - 3.10
 * Gym version - 0.21.0

### Additional context

Please let me know if I am missing anything regarding the implementation. Additionally, I would be happy to help contribute in resolving this issue.

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)
- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

:pencil: Please, don't forget to include more labels besides `bug` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @kad99kev!
Understood, I will take a look at it and I will comment you as soon as possible.

**Comment by AlejandroCN7** [comment]
Hi @kad99kev, I just detected the bug. In one of the recent versions of sinergym the variable called `Zone Lights Total Heating Rate` was added for both zones in the datacenter default observations. 

It turns out that the normalization wrappers need a range of values for each variable, as you can see in [constants.py](https://github.com/ugr-sail/sinergym/blob/main/sinergym/utils/constants.py). As I point out in issue #250, this is because we haven't found a way to read those ranges of values directly from the building IDF, so we have to run simulations, see the ranges of values it reaches and write them manually in a dictionary which is the one indicated in the wrapper's construction.

Sorry for the inconvenience, we will integrate the changes in the main branch.

**Comment by AlejandroCN7** [comment]
You have available the function `ranges_getter` in [common.py](https://github.com/ugr-sail/sinergym/blob/main/sinergym/utils/common.py). 

Just run your simulation (as many episodes as you want) with the **wrapper logger** active. Then, you run this function, passing the path of the experimentation folder as a parameter. This function reads all the subfolders of the available episodes and store the global maxima and minima values of each variable in a dictionary. Then you would have to update the range dictionary for that environment in [constants.py](https://github.com/ugr-sail/sinergym/blob/main/sinergym/utils/constants.py).

This is being covered with tests in PR #251, as well as adding some documentation for clarification. In any case, I have decided to delete the Zone Lights Total Heating Rate (Both Zones) variables from the default observation, as in principle it doesn't seem relevant to control the temperature setpoints, but you know how it can be added if you are going to use normalization ;). We will try to improve this part, as discussed in issue #250.

Thank you so much @kad99kev!
