### ISSUE TITLE
Installation problem

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#254]
Dear sinergym,

I followed the installation steps and downloaded the docker container. I cloned the repository and work in VS code now on a mac. I am getting the following error when trying the examples that were given:

<img width="1280" alt="image" src="https://user-images.githubusercontent.com/63644603/203946898-2edcccd5-1071-4e5b-b8ce-2cc60b978a55.png">

In the the plus_env.py file I set the path to my EnergyPlus and bcvtb as follows:

<img width="661" alt="image" src="https://user-images.githubusercontent.com/63644603/203947301-dc420fa2-2602-4a06-af22-c53880f59392.png">

Apparently I am doing something wrong here. I downloaded the version 22-1-0 of EnergyPlus for mac. The 9-5-0 download for linux download was not working on my mac. I did not get an folder like the newer version. May that be the problem? 

I hope you can help me with this problem!

Best,
Michiel

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens !
Are you sure you are using the downloaded container? If you are using it, Energyplus version 9.5.0 should already be installed, with an Ubuntu 22 OS.

If you are using the container, you should see "dev container" next to the project as in the attached image.
![Captura desde 2022-11-25 10-43-38](https://user-images.githubusercontent.com/23475034/203950346-fed55537-f266-4981-944a-cf48f68348ef.png)

At the same time, you should get the following in the vscode terminal without the need to install anything once you enter the container:
![Captura desde 2022-11-25 10-46-24](https://user-images.githubusercontent.com/23475034/203951271-67036edd-1d84-4217-890e-e1a62e93b108.png)

If you are inside the container, you should not change the value of EPLUS_PATH, as it points to the folder where the simulation engine is installed inside the container.

I hope this helps.

Regards, Alejandro.

**Comment by AlejandroCN7** [comment]
You have the next note in [installation documentation](https://ugr-sail.github.io/sinergym/compilation/main/pages/installation.html) if you are using vscode project:

![Captura desde 2022-11-25 10-50-57](https://user-images.githubusercontent.com/23475034/203953159-7814ab05-d535-4276-a508-57cfa0aca490.png)

The documentation cited in the note is [here](https://code.visualstudio.com/docs/devcontainers/containers).

**Comment by MichielKempkens** [comment]
Dear Alejandro,

Thank you for your response, I was indeed using the container in a wrong way. I can run the example files now. Thanks!

Best,
Michiel

**Comment by AlejandroCN7** [comment]
Great @MichielKempkens! Glad you found it helpful, I'll close this issue then :)

**Comment by SHITIANYU-hue** [comment]
Hi i have encountered same issue, but i didn't install with docker, i installed it manually, may i know if this is because i haven't installed energy plus?
![image](https://github.com/ugr-sail/sinergym/assets/38762389/3ccacd12-bd12-4dcb-b46f-028d41ee1fb2)
