### ISSUE TITLE
[How to simulate specific time period]

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#259]
### Question ❓

I am wondering how to simulate a specific time period while using the build in Open Ai algorithms. For example, I would like to simulate only one month for multiple episodes in order to track the progress. Also, how can I get more specific results. For now I only want to have the temperature in each zone and the energy use together with rewards. 

### Additional context

I am trying to perform some simple simulation with a short period of time in order to reduce running time. I want to compare simulation without RL with the different outcomes of the multiple algorithms provided. I want to compare the temperatures of the multiple thermal zones, energy consumption and rewards.

### Checklist

- ☑️  I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)

- ☑️  I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
The field you want to overwrite is `runperiod` and you have the documentation to change it [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/extra-configuration.html#extra-configuration-in-sinergym-simulations) and an example [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/extra-configuration.html#extra-configuration-in-sinergym-simulations).

About observation variables, you have documentation about it [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/environments.html#observation-action-spaces) and an example [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/notebooks/change_environment.html#Changing-observation-and-action-spaces).

**Comment by MichielKempkens** [comment]
Thanks! must have missed that part in the documentation
