### ISSUE TITLE
[Question] What is the evaluation scenario for the environments?

### ISSUE THREAD

**Issue by kad99kev** [ugr-sail/sinergym#263]
### Question ❓

Hello! Thank you for your help so far with Sinergym!

I had one question regarding the provided environments - what would be the evaluation scenario for them? For example in [Energym](https://github.com/bsl546/energym), they have provided [different weather files](https://bsl546.github.io/energym-pages/sources/ap2g.html#weather-files) and an [evaluation scenario](https://bsl546.github.io/energym-pages/sources/ap2g.html#evaluation-scenario). Is there an equivalent feature here? How can I use different weather files for a given environment if I would like to evaluate the model?

**Comment by AlejandroCN7** [comment]
Hello @kad99kev !
The evaluations we have right now use the stable baselines callbacks to evaluate the model every x training episodes. You can see it [here](https://github.com/ugr-sail/sinergym/blob/main/sinergym/utils/callbacks.py#L177). We use it in scripts/DRL_battery.py.

The agent is evaluated in its same environment, if you have weather variation enabled every year it will not be exactly the same climate, but it is always evaluated from the same configuration.

To evaluate an agent with different weathers than the trained one, you would have to load the obtained model and use it in a different environment that uses a different climate, for example.

I don't know if I answered your question correctly, I hope so! 

Regards.

**Comment by kad99kev** [comment]
Hi @AlejandroCN7,

Thank you! It makes sense. Is weather variation enabled by default for all environments? What is stochastic in `Eplus-5Zone-hot-continuous-stochastic-v1` when compared to the normal `Eplus-5Zone-hot-continuous-v1` environment?

**Comment by AlejandroCN7** [comment]
Hi @kad99kev,

`stochastic` is just what I am talking about, it is used to include variability in the weather episode by episode. You can change the nature of that variability using the [weather_variability](https://ugr-sail.github.io/sinergym/compilation/main/pages/environments.html#weather-variability) parameter in the environment constructor.

**Comment by kad99kev** [comment]
Thanks @AlejandroCN7,

Just to be clear, environments without the `stochastic` key by default are going to have the same weather each episode unless the `weather_variability` tuple is specified. For `stochastic` environments, this variability is by default enabled?

Lastly, in the image below, are the tuple parameters the values used for the `hot`, `mixed` and `cool` weather provided for different buildings like `5Zone`, `datacenter` etc. or are these just examples of how weather can be varied for the `hot`, `mixed` and `cool` environments?

![Screenshot 2023-01-05 at 4 35 00 PM](https://user-images.githubusercontent.com/43489154/210832197-084bd181-3c2d-42d8-b83d-1614c3a82ac6.png)

**Comment by AlejandroCN7** [comment]
Hi @kad99kev 

> Just to be clear, environments without the stochastic key by default are going to have the same weather each episode unless the weather_variability tuple is specified. For stochastic environments, this variability is by default enabled?

Yes, but not exactly. The environments where `stochastic` is present in their names, they have `weather_variability` specified. However, in environments where `stochastic` is not present, then `weather_variability` is not specified in their construction. When `weather_variability` is not defined, then it happens what you say; the same weather is used each episode. 

> Lastly, in the image below, are the tuple parameters the values used for the hot, mixed and cool weather provided for different buildings like 5Zone, datacenter etc. or are these just examples of how weather can be varied for the hot, mixed and cool environments?

It is only an example about how we can control the nature of that noise, changing the parameters (`weather_variability` tuple values). By default, the value of parameters for that weather variability is `(1.0, 0.0, 0.001)`.

You can see this in environment's specification [here](https://github.com/ugr-sail/sinergym/blob/main/sinergym/__init__.py) :).

**Comment by kad99kev** [comment]
Thank you so much for your explanation!
