### ISSUE TITLE
Sub-runs and thermal zones

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#265]
### Question ❓

Thank you very much for your help so far! 

I have still some questions about some things.

When I run for multiple episodes I got more subruns in the logger. For example, when I run 50 episodes for the DQN 126 subruns are created. How can that be the case? shouldn't it be one subrun per episode?

Also, when running the "Eplus-5Zone-hot-continuous-v1" environment, in the monitor.csv only the variables os SPACE1-1 are shown. However, their are multiple thermal zones 'plenum-1', 'space1-1', 'space2-1', 'space3-1', 'space4-1', 'space5-1'. How can I also get their variables? If I understand correctly they are also taken into account when calculating the Facility Total HVAC Electricity Demand Rate(Whole Building).

### Additional context

Im trying to compare different RL methods with a normal rule based simulation. Right know, on energy demand the rule base still outperforms RL but to reduce running time I am only simulating for one month with 25 episodes. What number of episodes would you recommend to get a good RL model?

I am trying to compare the energy use of an office.
How do you deal with the fact that the office is not used during nights/weekends. Or does the model take this already into account (with zone people occupant count)? Would you recommend tot create a comfort range for weekends? Just like you did with winter/summer? So you set a wider range on weekends in order to reduce energy usage? Or does this not make any sense at all? 

### Checklist

- [✔️  ] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [ ✔️ ] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by MichielKempkens** [comment]
In the results of my rule based simulation I set the setpoint for heating to 15 and for cooling to 25. Just to check what this will do for energy usage. Now, the energy demand is really high even though the indoor temperature is almost always in between setpoints. Maybe I don't understand correctly but in my reasoning the systems energy demand should be very low in this case. What other factors next to heating/cooling are affecting the total HVAC energy demand in my simulation?

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens!

> When I run for multiple episodes I got more subruns in the logger. For example, when I run 50 episodes for the DQN 126 subruns are created. How can that be the case? shouldn't it be one subrun per episode?

Are you including **evaluations** in your experiment? Evaluations are intermediate episodes that are run in the middle of the training to know how good the model you have at that moment is.

>  Also, when running the "Eplus-5Zone-hot-continuous-v1" environment, in the monitor.csv only the variables os SPACE1-1 are shown. However, their are multiple thermal zones 'plenum-1', 'space1-1', 'space2-1', 'space3-1', 'space4-1', 'space5-1'. How can I also get their variables? If I understand correctly they are also taken into account when calculating the Facility Total HVAC Electricity Demand Rate(Whole Building).

If you are using our default observation space for that building, you can see the next in utils.constants.py:

```python
DEFAULT_5ZONE_OBSERVATION_VARIABLES = [
    'Site Outdoor Air Drybulb Temperature(Environment)',
    'Site Outdoor Air Relative Humidity(Environment)',
    'Site Wind Speed(Environment)',
    'Site Wind Direction(Environment)',
    'Site Diffuse Solar Radiation Rate per Area(Environment)',
    'Site Direct Solar Radiation Rate per Area(Environment)',
    'Zone Thermostat Heating Setpoint Temperature(SPACE1-1)',
    'Zone Thermostat Cooling Setpoint Temperature(SPACE1-1)',
    'Zone Air Temperature(SPACE1-1)',
    'Zone Thermal Comfort Mean Radiant Temperature(SPACE1-1 PEOPLE 1)',
    'Zone Air Relative Humidity(SPACE1-1)',
    'Zone Thermal Comfort Clothing Value(SPACE1-1 PEOPLE 1)',
    'Zone Thermal Comfort Fanger Model PPD(SPACE1-1 PEOPLE 1)',
    'Zone People Occupant Count(SPACE1-1)',
    'People Air Temperature(SPACE1-1 PEOPLE 1)',
    'Facility Total HVAC Electricity Demand Rate(Whole Building)'
]
```

You can see the zone between brackets, if you want to add more observation variables, you can add the same variables but in different zone. By the moment, we have not included more variables to do the environment simpler. If you want to change that observation space, you can see an example [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/notebooks/change_environment.html#Changing-observation-and-action-spaces)

**Comment by AlejandroCN7** [comment]
> In the results of my rule based simulation I set the setpoint for heating to 15 and for cooling to 25. Just to check what this will do for energy usage. Now, the energy demand is really high even though the indoor temperature is almost always in between setpoints. Maybe I don't understand correctly but in my reasoning the systems energy demand should be very low in this case. What other factors next to heating/cooling are affecting the total HVAC energy demand in my simulation?

You mean you always leave the temperature setpoints fixed all year round? If the temperature difference with the outside is very high, this will lead to high energy consumption by HVAC.

**Comment by AlejandroCN7** [comment]
> What number of episodes would you recommend to get a good RL model?

It depends so much on the context of the experiment that I cannot give you a clear answer. The hyperparameters you use with the RL algorithm (with the algorithm type itself) is also a very influential factor in deciding how long to run a training.

**Comment by MichielKempkens** [comment]
Thank you for your answer @AlejandroCN7!

The reason that im asking these questions is that my problem is that my RL algorithm consumes much more energy than a rule based simulation. Also the comfort seems to be better.

My rule based simulation is:
Working hours (07:00-19:00) Heating setpoint 20, Cooling setpoint 23,5.
Weekends/Non-working hours, Heating setpoint 18, Cooling setpoint 25,5.

My RL based simulation:
summer comfort range (22;25,5)
winter comfort range (20;23,5)

When using the following env:


env = gym.make(environment, weather_file = weather,reward=LinearReward ,config_params = extra_params
                                                
                                                reward_kwargs={
                                                                    'temperature_variable': 'Zone Air Temperature (SPACE1-1)',
                                                                    'energy_variable': 'Facility Total HVAC Electricity Demand Rate(Whole Building)',
                                                                    'range_comfort_winter': (20.0, 23.5),
                                                                    'range_comfort_summer': (22.0, 26.0)
                                                                    ,'energy_weight': 0.6}) 

The comfort range is completely ignored in the reward.
I feel like when changing such variables in the reward.py these changes are not taking into account when simulating. 
I am using the PPO algorithm with continuous action space.
