### ISSUE TITLE
Set energy weight

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#268]
### Question ❓

I am trying to play around with the energy weight to get more energy efficient results. Therefore, I am changing the weights as follows:

env = gym.make(environment, weather_file = weather,reward=ExpReward ,config_params = extra_params,
                                                
                                                reward_kwargs={
                                                                    'temperature_variable': 'Zone Air Temperature (SPACE1-1)',
                                                                    'energy_variable': 'Facility Total HVAC Electricity Demand Rate(Whole Building)',
                                                                    'range_comfort_winter': (20.0, 23.5),
                                                                    'range_comfort_summer': (22.0, 26.0)
                                                                    ,'energy_weight': 0.6})

This results in the fact that comfort is not taken into account anymore in the reward function. Do you maybe know how this can be fixed?
 

### Additional context

I am trying to compare a rule-based simulation with multiple RL algorithms but the rule-based approach seems more energy efficient right now.

### Checklist

- [ ✔️ ] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [ ✔️ ] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

Are you sure that comfort is not being taken into account in the reward? The reward is a sum of penalties; energy on the one hand and comfort on the other hand. 

The reward is returned with the reward terms, check that dictionary and verify that it is disregarded:
```python
# Weighted sum of both terms
        reward = self.W_energy * reward_energy + \
            (1.0 - self.W_energy) * reward_comfort

        reward_terms = {
            'reward_energy': reward_energy,
            'total_energy': obs_dict[self.energy_name],
            'reward_comfort': reward_comfort,
            'abs_comfort': comfort,
            'temperatures': temps
        }

        return reward, reward_terms
```

**Comment by MichielKempkens** [comment]
Thank you for your answer.

That is exactly how it looks in my code. Whenever I add the 
reward_kwargs={
                                                                'temperature_variable': 'Zone Air Temperature (SPACE1-1)',
                                                                'energy_variable': 'Facility Total HVAC Electricity Demand Rate(Whole Building)',
                                                                'range_comfort_winter': (20.0, 23.5),
                                                                'range_comfort_summer': (22.0, 26.0)
                                                                ,'energy_weight': 0.6})

The comfort penalty is always zero in the monitor.csv. Also, the reward is just the energy_weight * power_penalty.

However when I don't add any reward_kwargs the comfort is taken into account with the default energy weight of 0.5

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

`Comfort penalty` is 0 when temperature is between range comfort, so that means that the temperature is correct in the zone indicated (`Zone Air Temperature (SPACE1-1)`) in the current timestep. You would have to check if zone temperature is correct in the same timestep you have a comfort penalty 0 before to think that comfort is not being taken into account.

I don't know if I have solved your question, let me know if not.
Regards.

**Comment by MichielKempkens** [comment]
Yes that was the case but I fixed it in another way. Thank you for your time!
