### ISSUE TITLE
[Question] Custom environment produces "invalid literal" error when receiving message from energyplus 

### ISSUE THREAD

**Issue by HannesGauch** [ugr-sail/sinergym#271]
### Question ❓

Have you come across non-interpretable messages from energyplus leading to errors?

### Additional context

I have set up a custom environment to use with sinergym. gym.make() runs successfully, but when I do env.reset() I get the error message:

**ValueError: invalid literal for int() with base 10: 'Ç|2'**

this occurs when disaggregating the first message received from energyplus in the line
sinergym/sinergym/simulators/eplus.py:539

`version = int(rcv[0])`

I was wondering if anyone has come across this problem and might know the cause for it?

Thank you!

**Comment by AlejandroCN7** [comment]
Hi @HannesGauch,

> Have you come across non-interpretable messages from energyplus leading to errors?

This kind of messages occur when there is some kind of problem with the simulation directly (not exactly with Sinergym).

> I was wondering if anyone has come across this problem and might know the cause for it?

In spite of the error you mention, an output folder will have been created from that execution. Check it and look in `<execution_output_folder>/<subrun_folder>/output/eplusout.err`.
There should be more information about the error you are getting with the "_Severe_" tag.

**Comment by HannesGauch** [comment]
Thank you @AlejandroCN7 !
The eplusout.err file is empty, unfortunately, and the idf file runs fine before modifiying it for sinergym.

I have pinned down the problem to the use of the observation variable:
"Environmental Impact Total CO2 Emissions Carbon Equivalent Mass(Whole Building)"
When i don't use this observation variable, the problem disappears.

Are there any known limitations to which variables can be used as observation variables (except that they have to be present in the .rdd file) ?

**Comment by HannesGauch** [comment]
Thanks again @AlejandroCN7!
I am not using Normalization wrapper, but I finally found my problem.

The key for the observation variable was wrong. Should have been "Site" instead of "Whole Building".
It might be worth changing sinergym.utils.config.Config._check_observation_variables() to allow for other keys than Zone names, "Whole Building" and "Environment".

Thanks again and best regards!

**Comment by AlejandroCN7** [comment]
Hi @HannesGauch,

Good to see you've solved it! 
In the last version (v2.2.0), observation variables check has been [updated ](https://github.com/ugr-sail/sinergym/pull/266/commits/a00839d7dd9f87c6b27b0ccea16f8ae3dd007f0c), now only check is done when variable type is `Zone`. As we find out more about the variables, we will add new checks, such as HVAC variable type. In any case, I plan to add checks like your comment about variable type is correct or not.

I close this issue, if you have any questions feel free to reopen this issue or create another one :). 
Thank you so much!
