### ISSUE TITLE
No good results

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#274]
### Question ❓

Right now I am performing simulations on the 5ZoneAutoDXVAV.idf file with a weather file of new york. I am comparing a simple rule based simulation with different simulations of RL. Right now, I tried PPO and DDPG with different parameters. The problem is that the rule based approach is always more energy efficient than the RL approached I tried. What could be the reason and how can I fix this problem. 

### Additional context

The rule based approach looks the following:
In working hours (7 until 19):
Heating setpoint = 20
Cooling setpoint = 23.5
Non-working hours and weekend:
Heating setpoint = 15
Cooling setpoint = 30

For the RL simulations I used an hourlyexp reward. So within working hours the energy weight is set to 0.5 (tried a lot of different energy weights) and in non-working hours and weekends the energy weight is 1. The comfort range is (20,23.5). The comfort range in non working and weekend is set to (15,30)

Right now I am only testing on the month January with 10 episodes to keep the running time relatively small.

I hope you can give me any advice on how to outperform the rule based scenario with RL. If you need more information please let me know.

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens , 

have you found a performing configuration working without sinergym? Sinergym is not intended to find the best algorithm/configuration (if any) and maybe the RL-based approach is indeed the best performing. There is plenty of ongoing research (including our own) on which could be promising parameters/RL algorithms for this task. We are precisely developing Sinergym so we can easily test many configurations and hypothesis while automatically logging the results. We hope that you are finding sinergym useful as well in such regard.

**Comment by MichielKempkens** [comment]
Hi @AlejandroCN7,

Thank you for your answer! Yes I understand. I was just wondering if I was doing something wrong here. Just want to mention that sinergym works perfect for the case I want to use it, which is test different RL algorithms and hypothesises. So thank you very much for helping me with sinergym.
