### ISSUE TITLE
Observations and new idf

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#275]
### Question ❓

Dear @AlejandroCN7,

Thank you very much for your help with sinergym. It really helps to easily perform simulations with RL. I have some questions regarding to some simulations I performed.

Is it possible to add more observation variables than in the variables file? I want to add the hour of the day. The reason is that it seems that my algorithm does not react much on comfort hours. Right now I have different comfort ranges during the day and night. It seems that is does not take the day range into account even if this gives really big negative rewards or even if positive rewards are given to stay in the range. The algorithm just keeps both heating and cooling setpoints very constant (below the daytime range). Do you maybe have any tips on that?

What is the best way to see the observation space. Does it only take the observations selected into account at that specific moment? For example, only the outdoor temperature or the solar radiation rate at that moment? Or can I also take the radiation rate of the next two hours into account?

Also, I want to introduce my own idf to sinergym. How can I add my own idf and weather file and create an environment?

Kind regards,
Michiel

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

> Is it possible to add more observation variables than in the variables file?

In variables file (RDD file) it is available all variables for that building model. About how you can add more variables to your observation, see [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/environments.html#observation-action-spaces) and an example [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/notebooks/change_environment.html#Changing-observation-and-action-spaces).

>  I want to add the hour of the day

Sinergym is already taking into account the time, day, month and year of each iteration. If you activate the loggerWrapper you will be able to see it in `monitor.csv`

> Does it only take the observations selected into account at that specific moment? For example, only the outdoor temperature or the solar radiation rate at that moment? Or can I also take the radiation rate of the next two hours into account?

That depends on the specific DRL algorithm you are using to build a control strategy, Sinergym takes care of applying an action once it is received from an external agent.

> Also, I want to introduce my own idf to sinergym. How can I add my own idf and weather file and create an environment?

Documentation --> [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/environments.html#adding-new-weathers-for-environments) and [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/environments.html#adding-new-buildings-for-environments)

**Comment by MichielKempkens** [comment]
hi @AlejandroCN7,

Thank you for explaining
