### ISSUE TITLE
Q-learning

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#277]
### Question ❓

Dear @AlejandroCN7,

Is it also possible to perform Q-learning with sinergym. I want to compare these results with DRL.

### Checklist

- [ ] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [ ] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

Of course, If you implement/find code that is compatible with OpenAI gym environments, you can integrate it with Sinergym in the same way as DQN is done in Stable Baselines, for example.

**Comment by MichielKempkens** [comment]
thanks
