### ISSUE TITLE
New files

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#282]
### Question ❓

Whenever I add files, for example weather files, they don't seem to be recognised in sinergym. I tried to add weather files to the weather folder but when using this file I get the: No such file or directory error. I also tried to change a weather file. I replaced the data of the Granada weather file with weather data from Amsterdam. When performing a simulation it still uses the Granada weather data even this data does not exist anymore in the weather folder. 

It seems that the path is referring to some "old" version of the weather folder. I followed the steps in [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/environments.html#adding-new-weathers-for-environments) but the files cannot be found. 

Do you know how I can fix this error?

Best,
Michiel

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

Please, can you give me more information? For example, the code you are using for testing and getting that error you comment.

**Comment by MichielKempkens** [comment]
Dear @AlejandroCN7,

As I was trying to fix this error, I deleted everything and started all over again. I cloned the repository again and created a dev container. 

Now I am getting other errors that I was not getting before. When trying to implement drl, I got "no module stable_baselines3. After pip install stable_baseline3 I get the following error:

<img width="710" alt="image" src="https://user-images.githubusercontent.com/63644603/218960246-3defac35-1ba6-4872-9b67-1720dedbc6f2.png">

Do you know how I can fix this?

Best,
Michiel

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,
We have included a warning box ⚠️ in [README](https://github.com/ugr-sail/sinergym#readme) for the latest version of Sinergym. We have implemented gymnasium compatibility, meanwhile Stable Baselines 3 is not adapted yet. If you want to use SB3 algorithms, use the version `2.2.0`.

**Comment by MichielKempkens** [comment]
Thanks! @AlejandroCN7,

Must have missed that one. 

When trying to pull that version in docker I get the Error "response from daemon: error creating temporary lease: read-only file system: unknown"

**Comment by MichielKempkens** [comment]
Issue is resolved, thank you!
