### ISSUE TITLE
Using version 2.2.0

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#287]
### Question ❓

Dear @AlejandroCN7,

Yesterday we had contact about an error I was receiving. To use the stable_baselines3 the best I could do was using version 2.2.0. While using that version I also got an error: 

<img width="1272" alt="image" src="https://user-images.githubusercontent.com/63644603/219317485-087b2454-72d3-4ebd-9b57-729b38e13ee3.png">

My question is if I am using the version correctly. In the left bottom you can see the version 2.2.0. But since I get the error "no module named 'gym'", I am not sure if I am using it in the right way.

I downloaded the latest version in docker, cloned the repository on GitHub and reopened it in container in vscode. After, I selected version 2.2.0 as tag in the left bottom in the screenshot.

Best,
Michiel

Add any other context about the question here.

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens!

I have been doing some research on the subject, try changing the following:
![Captura desde 2023-02-16 10-18-20](https://user-images.githubusercontent.com/23475034/219321916-deb02027-f08b-4a03-b247-e07d2fe855ee.png)

You have to change the line `"dockerFile": "./Dockerfile"` by `"dockerFile": "../Dockerfile"` in `.devcontainer/devcontainer.json`. Then, save the file (CTRL+s) ,and it will appear an advise to rebuild the container, do it. If this message doesn't appear, go to the remote explorer and rebuild the container manually.

Let me know if the error is solved.
Regards.

**Comment by AlejandroCN7** [comment]
If it works, it will be solved in the next Sinergym subversion :)

**Comment by MichielKempkens** [comment]
Everything seems to work perfectly fine again!

Thank you so much @AlejandroCN7! Much appreciated!!
