### ISSUE TITLE
New IDF Error

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#292]
### Question ❓

Dear @AlejandroCN7,

After adding a new building I get some error. It is possible to create an environment and to get the building specifics as described 
[here](https://ugr-sail.github.io/sinergym/compilation/main/pages/notebooks/change_environment.html#Getting-information-about-building-model-with-Sinergym). However when I try to perform a simulation I get an error that looks as follows: 

![image](https://user-images.githubusercontent.com/63644603/220370280-1f2f2548-cd08-4520-8e78-35292876bb4f.png)

As can be seen I try to perform some simple simulation with a Rule based controller. 

Have you ever experienced such an error?

Kind regards,
Michiel

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

When an unreadable message is received from the simulator, in most cases, it means that there is some kind of error in the definition of the building model (IDF).

I recommend you to have a look at `eplusout.err` and maybe you have more information. This file can be found inside the output folder following this [structure](https://ugr-sail.github.io/sinergym/compilation/main/pages/output.html).

I am sorry I cannot be of more help, but we only support the buildings we have included ourselves, as we do not know the nature and origin of the other buildings.

Regards,
Alejandro

**Comment by MichielKempkens** [comment]
Hi @AlejandroCN7,

Thanks for your answer. That is understandable, will try to fix it that way.  Thank you for your help zo far. I have sent you an email.

Kind regards,
Michiel
