### ISSUE TITLE
Evaluation with weather variability

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#304]
### Question ❓

Dear @AlejandroCN7,

I am  not sure how to perform validations on my trained model. Right now I have the following code:

![image](https://user-images.githubusercontent.com/63644603/224566337-73d4e9a4-a52a-4f83-86c4-4fee508c054b.png)

I want to validate my best model with the weather variability after running some test episodes. How do I do that? I got the feeling that I am mixing things up right now. 

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

Why are you setting `eval_freq` parameter in `LoggerEvalCallback` construction with value `n_timesteps_episode*episodes`? That value would be too big and evaluations will not happen never. `eval_freq` should be the number of episodes trained before the evaluation. For example, if you want to train in 10 episodes and execute 5 evaluations, then `eval_freq` should have value 2.

**Comment by MichielKempkens** [comment]
Hi @AlejandroCN7,

Thank you,  I had this value because I thought this the evaluation would take place after running the amount of episodes you set and not in between, but I will change that. 

Just to be sure, eval_freq should be: eval_freq=n_timesteps_episode * 2 in that case right? Just as the DRL [example](https://ugr-sail.github.io/sinergym/compilation/v2.2.0/pages/notebooks/drl.html).

For now it is only training on a specific weather file. That's fine but I only want the evaluations to be on the stochastic weather variability. How could I introduce this?

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

I think that notebook is wrong, thanks for pointing it out, I will fix it in later versions of the tool.
You should only specify value 2 directly (without timesteps multiplication).
See this: https://github.com/ugr-sail/sinergym/blob/8138a8f18a7518c93b3d697012d9d6ad2d2dcb34/scripts/DRL_battery.py#L100

I appreciate the reference to the notebook :)

**Comment by MichielKempkens** [comment]
However, how would I use the trained agent on the same environment that it was trained on but this time with weather variability. Otherwise evaluation would make sense right? 

Will it look something like this:
![image](https://user-images.githubusercontent.com/63644603/224753916-94275a55-ac68-4928-bb2b-e59d056e4e45.png)

So do you need to create a new environment? or will it not use the trained agent if you do it like this?

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

> I am not sure if it was wrong. When I just try 2 as a value it will create a massive amount of eval episodes. I guess after every 2 time steps. Maybe that is why the multiplication was done? To make sure it is evaluated after every 2 episodes?

Hoy many eval episodes generate? `eval_freq` should be episode number only (not timesteps).

>However, how would I use the trained agent on the same environment that it was trained on but this time with weather variability. Otherwise evaluation would make sense right?

You only have to use an environment with `stochastic` in the name. Those environemnts has weather variability, Sinergym will apply variability in each train and eval episode so you don't have to worry about it. Of course evaluation would make sense.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

> Just out of interest, If no stochasticity is used. How will the evaluation be performed since it using the same data as the model was trained on right?

In that case, the random component of the agent is covered in the evaluation only. In any case, it could be possible to evaluate the model in a different environment in which it has been training if you want.

> Also, would it make sense to train the model on the same data and only use weather variability on the evaluations, not in the training?

Weather variability is used in order to avoid overfitting and improve generalization in the agent. If you want to study the impact of this component is good, but if it is not the case, I recommend to use in the training process too.
