### ISSUE TITLE
Model does not converge

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#305]
### Question ❓

Dear @AlejandroCN7,

My model seems to not learn anything in its episodes. I tried a lot but it still does not seem to converge. For now I am simulation a DQN on the 5zone environment. I thought maybe the reason is that all the rewards are continuous and the model does not know sometimes how bad an action actually is so I tried the following reward:

If during office hours in temp range: comfort_reward = 100
else: comfort reward = -100
non-office hours in temp range: comfort_reward = 1
non-office hours not in temp range: comfort_reward = - 1

For the energy reward I did the following:
![image](https://user-images.githubusercontent.com/63644603/224938797-add19e6c-e127-4a07-ae9a-398f701a15d8.png)

Then I just use the linear reward with energy weight 0.5

The models cumulative and mean reward is not going up, although I see in monitor.csv that a lot of energy inefficient choices are made (heating for no reason during the night for 1 hour).

What could the reason be that the model is not learning? Have you experienced the same? 

best,
Michiel

### Checklist

- [ ] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [ ] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

Sinergym is a project focused on providing simulations and axes of freedom when setting the context of experiments. I don't know what to answer to particular experiments, as I am missing a lot of information. Perhaps DQN is not an algorithm that works well for the particular problem you want to solve, perhaps the manual option you have developed is not appropriate, perhaps the hyperparameters of the algorithm are not well tuned, etc. I can't recommend you on that. Experimentation and research with the use of the tool is beyond the scope of the project as such (although we are using it for the same purpose). If you have any questions regarding the tool or any bugs encountered, I will be happy to help.

**Comment by MichielKempkens** [comment]
Hi @AlejandroCN7,

Thanks for your answer, I get it. Were you able to make a model converge with the original sinergym reward function on one of the buildings included in sinergym?

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,
Yes, we do :)
Although we believe that the solutions are sub-optimal (we need more research)

**Comment by MichielKempkens** [comment]
Thank you for answering @AlejandroCN7!

I think my model does now as well but really slowly. Thank you for all your help
