### ISSUE TITLE
Visualisation of the policy

### ISSUE THREAD

**Issue by MichielKempkens** [ugr-sail/sinergym#312]
### Question ❓

Dear @AlejandroCN7,

Is there any way to visualise the policy in some way with sinergym? I want to visualise/explain the decisions the agent took in some states. I mainly use PPO and DQN.

Kind regards,
Michiel

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @MichielKempkens,

You can load the trained agent and execute it using Sinergym logger to get a CSV file of interactions between agent and environment. Then, you can visualize that information using matplotlib (for example). Take a look in 'scripts/load_agent.py' (you don't need to use that script if you don't want, but as example to see how to load a model).

Recently we have included WandB compability, see #306 (documentation updated too) in case you want to use it to monitor training data in real time or record evaluations there.
