### ISSUE TITLE
[Question] How to breakdown rewards as optimization objectives with finished runs?

### ISSUE THREAD

**Issue by HYDesmondLiu** [ugr-sail/sinergym#321]
### Question ❓

How to breakdown rewards as optimization objectives with finished runs? i.e., I have many finished experiments, however, I want to breakdown the rewards into the optimization objectives (thermal comfort and energy consumption). I have read the documents and still cannot find the information, may I know where could I find the data?

### Checklist

- [X ] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [ X] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

**Comment by AlejandroCN7** [comment]
Hi @HYDesmondLiu,
You have two options:

1. In reward class, it is returned the scalar value and `terms`. `terms` is a dictionary with more information about reward, and it is included in `info` dictionary in `env.step`method. This is all the info keys about reward: 

```python
reward_terms = {
            'reward_energy': reward_energy, # energy objective
            'reward_comfort': reward_comfort, # comfort objective
            'total_energy': obs_dict[self.energy_name],
            'abs_comfort': comfort,
            'temperatures': temps
        }
```

2. If you want to work directly with a reward vector in which each element is a reward objective, take a look to [MultiObjectiveReward wrapper](https://ugr-sail.github.io/sinergym/compilation/main/pages/wrappers.html#wrappers). Information about this wrapper is available [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/modules/sinergym.utils.wrappers.MultiObjectiveReward.html#sinergym.utils.wrappers.MultiObjectiveReward) too.

**Comment by AlejandroCN7** [comment]
Moreover, if you have your experiments executed, you can access to `reward,power_penalty,comfort_penalty` columns in `monitor.csv`, but the executions should be executed with `WrapperLogger` activated, you have information [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/wrappers.html#wrappers) and [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/output.html#output-format).

**Comment by HYDesmondLiu** [comment]
@AlejandroCN7  Thanks for the prompt replies. So, if I did not activate the `WrapperLogger` before running the experiments. There will be no data recording the energy consumed and thermal comfort penalty? Is there a way to reversely estimate the energy consumption and thermal comfort penalty?

**Comment by HYDesmondLiu** [comment]
> Moreover, if you have your experiments already executed, you can look for the `reward,power_penalty,comfort_penalty` columns in `monitor.csv`; this will work only if the executions had the `WrapperLogger` activated. You have information [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/wrappers.html#wrappers) and [here](https://ugr-sail.github.io/sinergym/compilation/main/pages/output.html#output-format).

I have tried this option, but there is no `monitor.csv` output. I wonder if this has something to do with the `NormalizeObservation`. Because in my setup I need the normalized observations, so I need to do normalization and the wrapper altogether. `env = NormalizeObservation(env,ranges=RANGES_5ZONE)
env = LoggerWrapper(env)`

**Comment by HYDesmondLiu** [comment]
> 2\. here

Thanks, I could get the information I need with the `info` feedback from stepping.
