### ISSUE TITLE
[Bug]: `PermissionError` when call `env.reset()`

### ISSUE THREAD

**Issue by ekaradon-Alexander** [ugr-sail/sinergym#334]
### Bug 🐛

I got a `PermissionError` exception when I call `env.reset()` for the second time. 

### To Reproduce

Run the following script. 

```python
import gymnasium as gym
import numpy as np

import sinergym


env = gym.make('Eplus-demo-v1')

# Call reset() for the first time.
obs, info = env.reset()

# Do some simple control.
action = env.action_space.sample()
env.step(action)

# Call reset() for the second time. 
env.reset()     # <-- Raise an exception. 

```

Traceback:
```bash
---------------------------------------------------------------------------
PermissionError                           Traceback (most recent call last)
Cell In[4], line 17
     14 env.step(action)
     16 # Call reset() for the second time. 
---> 17 env.reset()     # <-- Raise an exception. 

File ~/.pyenv/versions/3.10.11/envs/env_sinergym/lib/python3.10/site-packages/gymnasium/wrappers/order_enforcing.py:61, in OrderEnforcing.reset(self, **kwargs)
     59 """Resets the environment with `kwargs`."""
     60 self._has_reset = True
---> 61 return self.env.reset(**kwargs)

File ~/.pyenv/versions/3.10.11/envs/env_sinergym/lib/python3.10/site-packages/gymnasium/wrappers/env_checker.py:57, in PassiveEnvChecker.reset(self, **kwargs)
     55     return env_reset_passive_checker(self.env, **kwargs)
     56 else:
---> 57     return self.env.reset(**kwargs)

File ~/Workspace/sinergym/sinergym/envs/eplus_env.py:201, in EplusEnv.reset(self, seed, options)
    198     obs, info = self.simulator.reset(
    199         self.default_options)
    200 else:
--> 201     obs, info = self.simulator.reset(
    202         options)
    204 return np.array(obs, dtype=np.float32), info

File ~/Workspace/sinergym/sinergym/simulators/eplus.py:172, in EnergyPlus.reset(self, options)
    170 # End the last episode if exists
    171 if self._episode_existed:
--> 172     self._end_episode()
    173     self.logger_main.info(
    174         'EnergyPlus episode completed successfully. ')
    175     self._epi_num += 1

File ~/Workspace/sinergym/sinergym/simulators/eplus.py:495, in EnergyPlus._end_episode(self)
    492 time.sleep(1)
    494 # Kill subprocess
--> 495 os.killpg(self._eplus_process.pid, signal.SIGTERM)
    496 self._episode_existed = False

PermissionError: [Errno 1] Operation not permitted
```

### Expected behavior

The environment should be correctly reset, such that a new control process could be run from the beginning. 

### System Info

Describe the characteristic of your environment:
 * Describe how Sinergym was installed: pip
 * Sinergym Version: 2.3.1
 * OS: macOS 13.3
 * Python version: 3.10.11
 * Gymnasium version: 0.28.1
 * Versions of any other relevant libraries: EnergyPlus 9.5.0

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)
- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

:pencil: Please, don't forget to include more labels besides `bug` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @ekaradon-Alexander!

I can see from the specs that you are using a MacOS. We are supporting on Ubuntu 22.04 LTS, which is the OS we use to develop Sinergym (although it should work on other systems). From what I see in the Traceback, it seems that the `os` library wants to kill the process thread on the second reset (the first reset does not need to kill a previous process) and the interpreter does not have sufficient permissions to do so. I don't have very clear how privileges and permissions are handled in MAC. As I said before, we work on Ubuntu. I propose the following alternatives:

1. Use the Sinergym container in which Ubuntu is ready, the libraries and Python version needed and Energyplus installed.
2. Maybe giving more permissions to the Python interpreter or the user in MacOS may solve the problem too.

In any case, I will open a new branch and try to modify the code to see if there is a way to stop it from happening on MacOS users. In case I get something, I will reference this issue and it will be fixed. 

Thank you very much for reporting this issue, we appreciate it so much! :)

Best regards.

**Comment by AlejandroCN7** [comment]
Hi @ekaradon-Alexander!

I have created the next [branch](https://github.com/ugr-sail/sinergym/tree/bug/issue-334) in which could be solved the problem. Can you try to run this code there and tell me if it works? 
If the error persists, we will think other alternatives for MacOS.

Thank you so much!

**Comment by ekaradon-Alexander** [comment]
> Hi @ekaradon-Alexander!
> 
> I have created the next [branch](https://github.com/ugr-sail/sinergym/tree/bug/issue-334) in which could be solved the problem. Can you try to run this code there and tell me if it works? If the error persists, we will think other alternatives for MacOS.
> 
> Thank you so much!

I get no more `PermissionError` in macOS with this branch.
