### ISSUE TITLE
[Question] how to solve invalid literal for int() with base 10

### ISSUE THREAD

**Issue by chencjiajy** [ugr-sail/sinergym#336]
### Question ❓
I installed sinergym version 2.3.3 and 2.2.0, when I run the [example usage](https://ugr-sail.github.io/sinergym/compilation/main/pages/usage-example.html), both version got error in line `env.reset()`  ValueError: invalid literal for int() with base 10: '\n'
![企业微信截图_e8b0eec0-0a90-4f4e-863e-68e91215cfae](https://user-images.githubusercontent.com/19321967/237047389-f38f85e2-a2c0-4644-9bb0-b493b55ca376.png)

By the way, I installed energyplus 9.5.0, I can run the [quick start example](https://energyplus.net/quick-start#runsim) successfully.

### Additional context

I found there is a [similar issue](https://github.com/ugr-sail/sinergym/issues/271),  But I  didn't make any change of the example code you provide.

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

**Comment by AlejandroCN7** [comment]
Hi @chencjiajy!

I recommend you to use our container available in [DockerHub](https://hub.docker.com/r/sailugr/sinergym) or use Dockerfile directly. This will save you from having to deal with installation or configuration.

In any case, what is your system specification? Please, fill the following template:
 * Describe how Sinergym was installed: 
 * Sinergym Version: 
 * OS: 
 * Python version 
 * Gymnasium version:
 * Versions of any other relevant libraries:

When you have the `ValueError: invalid literal for int() with base 10: '\n'` it means that there is a problem in the communication with the Eplus simulator. In spite of the error you mention, an output folder will have been created from that execution. Check it and look in `<execution_output_folder>/<subrun_folder>/output/eplusout.err`.
There should be more information about the error you are getting with the "Severe" tag.

**Comment by chencjiajy** [comment]
@AlejandroCN7  
Thanks for reply, I'll try container later.
My system specification list:
how Sinergym was installed: I use command `pip install sinergym[extras]` to install sinergym
Sinergym Version: 2.3.3
OS: Ubuntu 20.04
Python version: 3.10
Gymnasium version: 0.28.1
Versions of any other relevant libraries:  energyplus 9.5.0,  bcvtb folder copied from https://github.com/zhangzhizza/Gym-Eplus/tree/master/eplus_env/envs

**Comment by AlejandroCN7** [comment]
@chencjiajy
I don't know what is your problem exactly. Try to install BCVTB from [here](https://simulationresearch.lbl.gov/bcvtb/Download) (if this is the problem, I will update the documentation) and check that `EPLUS_PATH` and `BCVTB_PATH` are configured correctly. 

On the other hand, have you been able to see `<execution_output_folder>/<subrun_folder>/output/eplusout.err` file? That log may contain valuable information about your problem.

**Comment by chencjiajy** [comment]
the `eplusout.err ` file is empty

**Comment by vgarciasc** [comment]
I have just faced the same problem as the original post when doing a clean installation of the environment today. Same versions of OS, Python, Sinergym, Gymnasium and EnergyPlus. Installing BCVTB from the provided link and updating the `BCVTB_PATH` solved my problem.

**Comment by AlejandroCN7** [comment]
@vgarciasc @chencjiajy 
Thank you so much for the information. I will update documentation :)
