### ISSUE TITLE
[Bug]: Duplicate Training Logs for Multiple Actors  Using LoggerCallback

### ISSUE THREAD

**Issue by KandBM** [ugr-sail/sinergym#344]
### Bug 🐛
When training a PPO with multiple multithreaded environments/actors, a tensorboard log is recorded for each thread.

### To Reproduce

Here is the first half of the script I'm using, which includes training. Selecting a number of actors greater then one causes LoggerCallback to record a training log for each actor. 

```python
import gym
import argparse
import datetime
import os
import numpy as np
import pandas as pd

from sinergym.utils.constants import RANGES_5ZONE, DEFAULT_5ZONE_OBSERVATION_VARIABLES, DEFAULT_5ZONE_ACTION_VARIABLES
from sinergym.utils.callbacks import LoggerCallback, LoggerEvalCallback
from sinergym.utils.wrappers import NormalizeObservation
from stable_baselines3 import PPO
from stable_baselines3.common.callbacks import EvalCallback, BaseCallback, CallbackList
from stable_baselines3.common.vec_env import DummyVecEnv
from stable_baselines3.common.env_util import make_vec_env
from ppo_agent import ActorCriticPolicy
from results_parser import plot_results_figures

parser = argparse.ArgumentParser()
parser.add_argument('--mode', '-mode', type=str, default='training', required=True)
parser.add_argument('--episodes', '-ep', type=int, default=1)
parser.add_argument('--test_steps', type=int, default=3000)
parser.add_argument('--learning_rate', '-lr', type=float, default=.0007)
parser.add_argument('--n_steps', '-n', type=int, default=5)
parser.add_argument('--gamma', '-g', type=float, default=.99)
parser.add_argument('--gae_lambda', '-gl', type=float, default=1.0)
parser.add_argument('--ent_coef', '-ec', type=float, default=0)
parser.add_argument('--vf_coef', '-v', type=float, default=.5)
parser.add_argument('--max_grad_norm', '-m', type=float, default=.5)
parser.add_argument('--rms_prop_eps', '-rms', type=float, default=1e-05)
parser.add_argument('--random_seed', '-rs', type=int, default=1919788)
parser.add_argument('--n_actors', '-na', type=int, default=1)
parser.add_argument('--minibatch', '-mb', type=int, default=64)
parser.add_argument('--description', '-d', type=str, default=None)
parser.add_argument('--experiment_id', '-id', type=int, default=None)
parser.add_argument('--results_directory', '-dir', type=str, default=None)
parser.add_argument('--results_figures', '-fig', type=bool, default=True)
args = parser.parse_args()

env_id = 'Eplus-5Zone-mixed-continuous-stochastic-v3' if args.mode == 'test'\
        else 'Eplus-5Zone-mixed-continuous-stochastic-v2'
n_episodes = args.episodes

if not args.results_directory:
    name = 'PPO-' + env_id + '-' + args.mode
    experiment_date = datetime.datetime.today().strftime('%Y-%m-%d_%H:%M')
    if args.random_seed:
        name += '-seed-' + str(args.random_seed)
    if args.experiment_id:
        name += '-id-' + str(args.experiment_id)
    name += '_' + experiment_date
else:
    name = args.results_directory

model_path = f'./project/5zones_building/results/{name}'
if args.results_directory and not os.path.exists(model_path):
    os.makedirs(model_path)

env = gym.make(env_id)
env = NormalizeObservation(env, ranges=RANGES_5ZONE)

if args.mode == 'training':
    #defines vectorized env, but does not avg rwds over rollout...
    vec_env = make_vec_env(
        env_id, 
        n_envs=args.n_actors, 
        seed=args.random_seed, 
        wrapper_class=NormalizeObservation, 
        vec_env_cls=DummyVecEnv, 
        wrapper_kwargs=dict(ranges=RANGES_5ZONE)
        )

    model = PPO(
        ActorCriticPolicy,
        vec_env,
        verbose=1,
        learning_rate=args.learning_rate,
        n_steps=args.n_steps,
        batch_size=args.minibatch,
        gamma=args.gamma,
        gae_lambda=args.gae_lambda,
        ent_coef=args.ent_coef,
        vf_coef=args.vf_coef,
        max_grad_norm=args.max_grad_norm,
        seed=args.random_seed,
        tensorboard_log=model_path
    )

    n_timesteps_episode = env.simulator._eplus_one_epi_len / env.simulator._eplus_run_stepsize
    timesteps = n_episodes * n_timesteps_episode

    #env = DummyVecEnv([lambda: env])

    freq = 2  # evaluate every N episodes
    eval_callback = LoggerEvalCallback(
        vec_env,
        best_model_save_path=model_path + '/',
        log_path=model_path + '/', 
        eval_freq=max(n_timesteps_episode*freq//args.n_actors, 1), #https://stable-baselines3.readthedocs.io/en/master/guide/callbacks.html#evalcallback
        deterministic=False, 
        render=False, 
        n_eval_episodes=1
    )
    log_callback = LoggerCallback(sinergym_logger=False)
    callback = CallbackList([log_callback, eval_callback])

    # Training
    model.learn(total_timesteps=timesteps, callback=callback, log_interval=100)
    model.save(model_path + '/trained_model')

```

### Expected behavior

I would expect a single tensorboard log to be recoded during training. SB3 handles this by recording the average for all actors in a rollout.

### System Info

Describe the characteristic of your environment:
 * Describe how Sinergym was installed: Docker
 * Sinergym Version: 2.2.0
 * OS: e.g. Ubuntu 22.04 LTS
 * Python version e.g. 3.10
 * Gymnasium version: gym 2.1.0
 * Versions of any other relevant libraries: stabile-baselines3 1.7.0

### Additional context

I'm trying to reduce the wall time while training a PPO by using multiple multiprocessed actors, however training progress is difficult to understand with multiple logs.

### Checklist

- [X] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)
- [X] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [X] I have provided a minimal working example to reproduce the bug (**required**)

:pencil: Please, don't forget to include more labels besides `bug` if it is necessary.

**Comment by AlejandroCN7** [comment]
@KandBM thank you so much for reporting this issue! 
No multi-actor tests have been performed on Sinergym for the moment, we will try to find a solution as soon as possible.

**Comment by KandBM** [comment]
@AlejandroCN7 no worries! Since stable-baselines3 already averages the results among rollouts, maybe their implementation could provide some guidance? Otherwise is there a particular reason for using Sinergym's LoggerCallback over SB3's logging methods? If not I'll play around with that and report back

**Comment by AlejandroCN7** [comment]
Hi @KandBM,
Sinergym's LoggerCallback is an adaptation of SB3's logging in order to monitor specific information about building environments. Therefore, you are right! Their implementation could help to solve this issue. We will work on it as soon as possible, sorry for the delay.

**Comment by AlejandroCN7** [comment]
Hello!

As I said, Sinergym currently does not support vectorized environments, since the tool has not been tested with them. However, it may be upgraded in a future version. At the moment, I don't understand why you get the logs in different threads if SB3 is supposed to do averages, I understand that in some of the changes we made to adapt it to our needs we broke that.

So I recommend that you use the SB3 default callbacks. You will have all the training process information available, but will be missing concrete building information.

Finally, there may be problems with the Energyplus API for version 3.0 as I show below:

```bash
Exception ignored on calling ctypes callback function: <��H�H�~ object at 0x7f352bdb47c0>
Traceback (most recent call last):
  File "/usr/local/EnergyPlus-23-1-0/pyenergyplus/runtime.py", line 221, in run_energyplus
    return self.api.energyplus(state, len(args_with_program_name), cli_args)
TypeError: '��H�H�~' object does not support vectorcall
```

You can try with previous versions of Sinergym while we give a solution to this problem.

Best regards!
