### ISSUE TITLE
[Question] Custom runperiod leads to invalid base 10

### ISSUE THREAD

**Issue by RaphaelGoettfried** [ugr-sail/sinergym#349]
### Question ❓

When using a runperiod time that's only, for example, 6 months long. While my model is learning I get the error: 
`  File "/sinergym/sinergym/envs/eplus_env.py", line 231, in step
    obs, terminated, truncated, info = self.simulator.step(action_)
  File "/sinergym/sinergym/simulators/eplus.py", line 314, in step
    = self._disassembleMsg(rcv)
  File "/sinergym/sinergym/simulators/eplus.py", line 581, in _disassembleMsg
    nDb = int(rcv[2])
ValueError: invalid literal for int() with base 10: '\n'`

Is the runperiod only working for more than a year or should it even work with only a month?
### Additional context
I looked into the eplusout.err and the severe error i get is "ExternalInterface: Received end of simulation flag at time = 1464.00 hours." But I don't know if this is leads to the ValueError. Also I'm using the Docker Image, so bcvtb should be installed correctly.

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @RaphaelGoettfried!
Can you write the runperiod you are trying to use? Including the init and end year, please.

**Comment by RaphaelGoettfried** [comment]
Hey @AlejandroCN7, sure 1, 6, 2022 - 30, 9, 2022 and 1, 10, 2021 - 31, 5, 2022 are both periods that aren't working on my side.

**Comment by AlejandroCN7** [comment]
@RaphaelGoettfried I will check it, thank you so much for the report!
Can you send me the code you are trying to execute? And can you fill the next template, please?

Describe the characteristic of your environment:
 * Describe how Sinergym was installed: e.g. pip, docker, source, ...
 * Sinergym Version: e.g. 2.3.0
 * OS: e.g. Ubuntu 22.04 LTS or Sinergym container image
 * Python version e.g. 3.10 or Sinergym container
 * Gymnasium version:
 * Versions of any other relevant libraries:
