### ISSUE TITLE
Observed Minutes start at 1 and go to 60

### ISSUE THREAD

**Issue by mrks-g** [ugr-sail/sinergym#364]
### Question ❓

Why do the minutes of the observed time variables not start at 0 but end at 60? 

### Additional context

I set the observable time variables  DEFAULT_TIME_VARIABLES = ['year', 'month', 'day_of_month', 'hour', 'minutes']. 
My observation returned by the step function starts with minutes = 2 and ends with minute 60.
Any idea why this is the case?

### Checklist

- [ ] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [ ] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @mrks-g!

Simulations with EnergyPlus API skip a step after `reset()` call. I don't know why exactly, but I think it is due to the warmup process.
