### ISSUE TITLE
[Question] How to get the names of the observations? 

### ISSUE THREAD

**Issue by HYDesmondLiu** [ugr-sail/sinergym#375]
### Question ❓

I want to get the names of the observations in an environment (e.g., Eplus-5Zone-mixed-continuous-stochastic-v1 is with observations: Facility Total HVAC Electricity Demand Rate(Whole Building), People Air Temperature(SPACE1-1 PEOPLE 1), and so on... )
"
I looked up the documents and found using `env.get_wrapper_attr('observation_variables')` might be a solution.

However, in my environment, I cannot find this method: `env.get_wrapper_attr('observation_variables')`

### Additional context
Codes:
```
import gym
import sinergym
from sinergym.utils.wrappers import NormalizeObservation
from sinergym.utils.constants import RANGES_5ZONE

env = gym.make('Eplus-5Zone-mixed-continuous-stochastic-v1')
env = NormalizeObservation(env,ranges=RANGES_5ZONE)
env.get_wrapper_attr('observation_variables')

```

Error:
`*** AttributeError: 'EplusEnv' object has no attribute 'get_wrapper_attr'`

### Checklist

- [X] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [X] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

**Comment by AlejandroCN7** [comment]
Hi @HYDesmondLiu!

Can you tell me the exact version of Sinergym you are using? Judging by the code you show, you are using an old version where this attribute does not yet exist. This might work for you:

`env.variables['observation']` which has the observation variables names in the same order as the observation returned by env.step() method.

**Comment by HYDesmondLiu** [comment]
Hi @AlejandroCN7,
    Thanks for the reply, it works.
