### ISSUE TITLE
Why are the action and observation always out of sync? [Question]

### ISSUE THREAD

**Issue by jingjijiji** [ugr-sail/sinergym#404]
### Question ❓

when i try the bacic_example.ipynp, i found that actions do not take effect immediately, but rather after two steps. Why is that?

### Additional context

Add any other context about the question here.

### Checklist

- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)

:pencil: Please, don't forget to include more labels besides `question` if it is necessary.

**Comment by AlejandroCN7** [comment]
Hi @jingjijiji !

This is due to the functioning of the EnergyPlus API which is what Sinergym uses as middleware. It has a delay from the time the action is sent until the change occurs in the building, usually two steps as you mentioned. At the moment, I have no more information about it.
