### ISSUE TITLE
[Question]The state I get not match with my action

### ISSUE THREAD

**Issue by cainiaodidi** [ugr-sail/sinergym#405]
example code as below
```python
def func()
  action = agent.act(state)
  next_state, reward, done, truncated, info = env.step(action)
```

I found that the  observation of actuator  in next_state is not equal to which in action but equal it two steps later, for example:
t : action = 1 observation = 0
t+1: action = 2 observation = 0
t+3: action = 3 observation = 1
t+4 :action = 4 observation = 2

**Comment by AlejandroCN7** [comment]
Hi @cainiaodidi,
Duplicate, the answer can be found in the issue #404
