### ISSUE TITLE
[Bug]: Unnecessary rows recorded in monitor.csv

### ISSUE THREAD

**Issue by Miguel-jp** [ugr-sail/sinergym#415]
### Bug 🐛
When using the “Eplus-officegrid-mixed-continuous-v1” environment, the "monitor.csv" output by the Logger Wrapper starts recording results from July 21, regardless of the start date setting.

### To Reproduce

```python
import gymnasium as gym
import numpy as np
import sinergym
from sinergym.utils.wrappers import *

env=gym.make('Eplus-officegrid-mixed-continuous-v1')
env=LoggerWrapper(env)

env.reset()
truncated = terminated = False
current_month = 0
while not (terminated or truncated):
    a = env.action_space.sample()
    _,_,terminated,truncated,_=env.step(a)
env.close()
```

Running this will record the data starting on July 21 in "monitor.csv".

<img width="960" alt="0" src="https://github.com/ugr-sail/sinergym/assets/64046907/0ec00aa4-2c31-4f44-bc7a-15dd81793132">

After several iterations of the July 21 record, the record finally begins on January 1, the original start date.

<img width="960" alt="1" src="https://github.com/ugr-sail/sinergym/assets/64046907/fdd4412e-0552-4024-96de-a70a6065d9c7">

### Expected behavior

Records from January 1 should be recorded in "monitor.csv". Note that when the “Eplus-5zone-hot-discrete-v1” environment was used, the data is recorded from January 1 without any problems.

<img width="960" alt="2" src="https://github.com/ugr-sail/sinergym/assets/64046907/d0bf2bf0-f3b4-411e-b79c-b3dc5ec0fd7c">

### System Info

 * Sinergym was installed via docker (sailugr/sinergym:latest)
 * Sinergym Version: 3.3.5

### Checklist

- [x] I have checked that there is no similar [issue](https://github.com/ugr-sail/sinergym/issues) in the repo (**required**)
- [x] I have read the [documentation](https://ugr-sail.github.io/sinergym/compilation/html/index.html) (**required**)
- [x] I have provided a minimal working example to reproduce the bug (**required**)

**Comment by AlejandroCN7** [comment]
Hi @Miguel-jp!

This is due to the building SimulationControl configuration:

```
"SimulationControl": {
        "SimulationControl 1": {
            "do_hvac_sizing_simulation_for_sizing_periods": "No",
            "do_plant_sizing_calculation": "Yes",
            "do_system_sizing_calculation": "Yes",
            "do_zone_sizing_calculation": "Yes",
            "maximum_number_of_hvac_sizing_simulation_passes": 1,
            "run_simulation_for_sizing_periods": "Yes",
            "run_simulation_for_weather_file_run_periods": "Yes"
        }
}
```

Sizing periods are run at the beggining of the simulation. If you don't want these timesteps, you should set the `run_simulation_for_sizing_periods` and `do_plant_sizing_calculation` to `No`, in the building file epJSON like this:

```
"SimulationControl": {
        "SimulationControl 1": {
            "do_hvac_sizing_simulation_for_sizing_periods": "No",
            "do_plant_sizing_calculation": "No",
            "do_system_sizing_calculation": "Yes",
            "do_zone_sizing_calculation": "Yes",
            "maximum_number_of_hvac_sizing_simulation_passes": 1,
            "run_simulation_for_sizing_periods": "No",
            "run_simulation_for_weather_file_run_periods": "Yes"
        }
    },
```

In other buildings this is set as default, it will be updated in future versions for this building.

Thank you so much for the information.
