### ISSUE TITLE
[Documentation]: the website is 404.

### ISSUE THREAD

**Issue by YuBai630** [ugr-sail/sinergym#446]
### Documentation 📚

Hi, thanks for your project, I am studying with the doucmentation. I have found the websit is 404 from yesterday to now.
The website is :
https://ugr-sail.github.io/sinergym/compilation/main/index.html

**Comment by AlejandroCN7** [comment]
Hi @YuBai630!

Yes, I am working on that. it will be available again soon :)

**Comment by AlejandroCN7** [comment]
Fixed!

**Comment by YuBai630** [comment]
Thank you very much!

**Comment by YuBai630** [comment]
> Fixed!

Oh! The website is 404 again. TAT
