### ISSUE TITLE
[Bug]:Sinergym 3.6.12 cannot be started properly.

### ISSUE THREAD

**Issue by shudabee** [ugr-sail/sinergym#462]
# Bug Report: Sinergym 3.6.12 Cannot Be Started Properly

## Description
When running the `sailugr/sinergym:latest` Docker container, the `sinergym` script fails to start due to a `ModuleNotFoundError` for the `NormalizeReward` module in the `gymnasium.wrappers.normalize` package. This suggests an issue with the compatibility between `sinergym` and the installed version of `gymnasium` within the Docker image.

---

## Steps to Reproduce

1. Pull the `sinergym` Docker image:
   ```bash
   docker pull sailugr/sinergym:latest
   ```

2. Run the Docker container:
   ```bash
   docker run -it sailugr/sinergym:latest
   ```

3. Observe the error:
   ```plaintext
   Traceback (most recent call last):
     File "/workspaces/sinergym/scripts/try_env.py", line 5, in <module>
       from gymnasium.wrappers.normalize import NormalizeReward
   ModuleNotFoundError: No module named 'gymnasium.wrappers.normalize'
   ```

---

## Expected Behavior
The `sinergym` script should run without errors, initializing the environment properly.

---

## Actual Behavior
The container exits unexpectedly with the following error:
   ```plaintext
   Traceback (most recent call last):
     File "/workspaces/sinergym/scripts/try_env.py", line 5, in <module>
       from gymnasium.wrappers.normalize import NormalizeReward
   ModuleNotFoundError: No module named 'gymnasium.wrappers.normalize'
   ```

---

## Environment Details

- **sinergym version**: 3.6.12 (Docker image)
- **gymnasium version**: 1.0.0 (pre-installed in Docker image)
- **Python version**: 3.12 (pre-installed in Docker image)
- **Docker image**: `sailugr/sinergym:latest`  
  **Image ID**: `9669f1cae4fc`

---

## Additional Information

The error suggests that the `gymnasium` version included in the Docker image does not contain the `NormalizeReward` module, which is required by `sinergym`. This may be due to a mismatch between the versions of `sinergym` and `gymnasium`.

**Comment by shudabee** [comment]
ADD:
I download the image directly from Docker hub, instead of building it from github and build it. These two different methods may cuase the issue?

**Comment by AlejandroCN7** [comment]
Hello @shudabee,

Apologies for the inconvenience. When we updated to ensure compatibility with gymnasium>=1.0.0, all the necessary adjustments were made to the Sinergym package. However, that specific script wasn’t updated, which is why it causes an error when running in the container.

I’ve just fixed the issue in a hotfix. It should now work correctly in `latest` tag and in the upcoming v3.7.0 release. 😊

Thank you for sharing the information—it was incredibly helpful.
Best regards!
